useTabs = true
tabWidth = 3
printWidth = 100
#endOfLine = "lf"

# -- Not supported yet --
# trailingComma = "es5"
# embeddedLanguageFormatting = "auto"

# Example override
#overrides = [
#  { files = ["tests/*.rs"], options = { printWidth = 80 } }
#]